### ISSUE TITLE
Não consigo fazer meu PR

### ISSUE THREAD

**Issue by yuripramos** [Personare/front-end-challenge#6]
Boa noite pessoal, terminei (nunca acaba né rs) meu projeto e não sei o porquê ele não encontra uma diff entre o meu branch que dei fork da master de vocês, estou pesquisando aqui, mas estão me recomendando voltar todos os commits e ir dando cherry-pick, achei arriscado.

Eu recebo este erro : _There isn’t anything to compare.
Personare:master and yuripramos:yuri_ramos are entirely different commit histories._

Anyway... meu repositório está aqui, só não consigo dar PR :( 

https://github.com/yuripramos/front-end-challenge/tree/yuri_ramos

**Comment by caueops** [comment]
Oi @yuripramos, tudo bem?

Obrigado por realizar o nosso desafio, já podemos fazer o Code Review dele?

**Comment by yuripramos** [comment]
Olá @ceasbz, ainda não fiz os testes, estive muito ocupado essa semana que passou, terminarei durante essa semana e versiono nesse repositório...

**Comment by caueops** [comment]
Sem problemas @yuripramos,

Era só pra saber mesmo se poderíamos realizar o Code Review \o

Assim que fechar é só falar ^.^

**Comment by yuripramos** [comment]
@ceasbz Boa noite, mil perdões pela demora na entrega, acabei relaxando por não haver prazos e ter muitas coisas à fazer no trabalho. Contudo terminei o App, pode fazer o Code Review \o

**Comment by caueops** [comment]
Beleza @yuripramos,

Obrigado por enviar o desafio 💃
